spring:
  datasource:
    url: jdbc:postgresql://dpg-cpulfj6ehbks73ek1hgg-a.render.com/go2uz_db
    username: go2uz_user
    password: CxKRD9jLGwq3CfxuCOJCRrwOm3zyEZQs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none







